name: Sea Salt Learning
favicon: null
layout_spectrum: 0.57903
typography_spectrum: 0.82475
title: Sea Salt Learning helps organisations get fit for the SOCIAL AGE.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.6875
  lightness: 0.9375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
