name: Sea Salt Learning
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48494
title: Sea Salt Learning helps organisations get fit for the SOCIAL AGE.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d3acbe'
    - '#fefefe'
    - '#e37540'
    - '#666261'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
