analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.814144
  lightness: 0.75
  rhythmicContrast: 0.75
  saturation: 0.236019
cta: {}
layout_spectrum: 0.977796
name: Sea Salt Learning
opengraph: {}
purpose: []
typography_spectrum: 0.749177
