analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.4375
  lightness: 0.494243
  rhythmicContrast: 0.756578
  saturation: 0.236019
cta: {}
layout_spectrum: 0.69617
name: Sea Salt Learning
opengraph: {}
purpose: []
typography_spectrum: 0.53227
