name: Sea Salt Learning
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48494
title: Exploring the Social Age
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
