analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.888157
  lightness: 0.392269
  rhythmicContrast: 0.120888
  saturation: 0.625
cta: {}
layout_spectrum: 1
name: Sea Salt Learning
opengraph: {}
purpose: []
typography_spectrum: 0.45148
