analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.5
  lightness: 0.875
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 1
name: Sea Salt Learning
opengraph: {}
purpose: []
typography_spectrum: 0.48494
