name: Sea Salt Learning
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.53227
title: Sea Salt Learning helps organisations get fit for the SOCIAL AGE.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#baa379'
    - '#5b8699'
    - '#5d625e'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
